apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wisdom-certificate
  namespace: sock-shop
spec:
  secretName: wisdom-secret
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: wisdomgoddy.me
  dnsNames:
  - wisdomgoddy.me
 